version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template-golang
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default

networks:
  default:
    driver: bridge
